# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!


# The VM Setup for the attack looks like this. 

# OPEN5GS [.100 & .101] <---> AMF-Only [.102] <---> GNB-Only [gNodeBs at .120 & .121] <---> UE [at .130]
#                                                      |----------------------------------> UE [at .131]

# Variables
OPEN5GS_IPv4_ADDR = "192.168.56.100"
UPF_OPEN5GS_IPv4_ADDR = "192.168.56.101"
AMF_OPEN5GS_IPv4_ADDR = "192.168.56.102"
RAN1_IPv4_ADDR = "192.168.56.120"
RAN2_IPv4_ADDR = "192.168.56.121"
UE1_IPv4_ADDR = "192.168.56.130"
UE2_IPv4_ADDR = "192.168.56.131"

Vagrant.configure("2") do |config|
  config.vm.box = "../package.box"
  def_provider = "virtualbox"

  # The following folders shall be synced and loaded in all VMs 
  config.vm.synced_folder "configs", "/configs"
  config.vm.synced_folder "scripts", "/scripts"


  # VM #1: OPEN5GS 5G core network (All-in-one - but AMF)
  config.vm.define "open5gs" do |open5gs|
    open5gs.vm.network "private_network", ip: OPEN5GS_IPv4_ADDR
    open5gs.vm.network "private_network", ip: UPF_OPEN5GS_IPv4_ADDR

    open5gs.vm.provider def_provider do |vb|
     # Customize the amount of cpu & memory on the VM:
     vb.name = "open5gs"
     vb.memory = "1024"
     vb.cpus = "1"
    end

    open5gs.vm.provision "shell", :privileged => true, inline: <<-SHELL
      echo "---------Removing UERANSIM--------"
      sudo rm -rf /home/vagrant/UERANSIM
      echo "---------Finished installing Open5GS ------"
    SHELL
    
    # Setting up NAT for the VM
    open5gs.trigger.after :up do |trigger|
      trigger.name = "Finished Message"
      trigger.info = "Machine is up!"
      open5gs.vm.provision :shell, :run => 'always', :privileged => true, inline: <<-SHELL
        # This script will run everytime that the system bootsup 
        echo "--- Adding a route for the UE to have WAN connectivity over SGi/N6 -------"
        sudo sh /home/vagrant/open5gs/misc/netconf.sh
        ### Enable IPv4/IPv6 Forwarding
        sudo sysctl -w net.ipv4.ip_forward=1
        sudo sysctl -w net.ipv6.conf.all.forwarding=1
        ### Add NAT Rule
        sudo iptables -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o ogstun -j MASQUERADE
        sudo ip6tables -t nat -A POSTROUTING -s 2001:db8:cafe::/48 ! -o ogstun -j MASQUERADE

      SHELL
    end
  end

  # VM #2 : OPEN5GS 5G core network (AMF Only)
  config.vm.define "amf-only" do |amf|
    amf.vm.network "private_network", ip: AMF_OPEN5GS_IPv4_ADDR
    
    amf.vm.provider def_provider do |vb|
     # Customize the amount of cpu & memory on the VM:
     vb.name = "amf-only"
     vb.memory = "1024"
     vb.cpus = "1"
    end

    amf.vm.provision "shell", :privileged => true, inline: <<-SHELL
      echo "---------Removing UERANSIM--------"
      sudo rm -rf /home/vagrant/UERANSIM
      echo "---------Finished installing Open5GS ------"      
    SHELL
    
  end

  # VM #3 : UERANSIM as RAN (gNB) Simulator
  config.vm.define "gnb-only" do |ueransim|
    ueransim.vm.network "private_network", ip: RAN1_IPv4_ADDR
    ueransim.vm.network "private_network", ip: RAN2_IPv4_ADDR

    ueransim.vm.provider def_provider do |vb|
    # Customize the amount of cpu & memory on the VM:
    vb.name = "gnb-only"
     vb.memory = "1024"
     vb.cpus = "1"
    end

    # #Enable provisioning with a shell script.
    ueransim.vm.provision "shell", inline:<<-SHELL 
      echo "---------Removing open5gs --------"
      sudo rm -rf /home/vagrant/open5gs
      echo "---------Finished installing UERANSIM ------"           
    SHELL
  end
  
  # VM #4 : UERANSIM as benign (UE) Simulator
  config.vm.define "benign-ue-only" do |ueransim|
    ueransim.vm.network "private_network", ip: UE1_IPv4_ADDR

    ueransim.vm.provider def_provider do |vb|
    # Customize the amount of cpu & memory on the VM:
    vb.name = "benign-ue-only"
     vb.memory = "1024"
     vb.cpus = "1"
    end

    # #Enable provisioning with a shell script.
    ueransim.vm.provision "shell", inline:<<-SHELL 
      echo "---------Removing open5gs --------"
      sudo rm -rf /home/vagrant/open5gs
      echo "---------Finished installing UERANSIM ------"     
    SHELL
  end

  # VM #5 : UERANSIM as malicious (UE) Simulator
  config.vm.define "mal-ue-only" do |ueransim|
    ueransim.vm.network "private_network", ip: UE2_IPv4_ADDR

    ueransim.vm.provider def_provider do |vb|
    # Customize the amount of cpu & memory on the VM:
      vb.name = "mal-ue-only"
      vb.memory = "2048"
      vb.cpus = "2"
    end

    # Enable provisioning with a shell script.
    ueransim.vm.provision "shell", inline:<<-SHELL 
      echo "---------Removing open5gs --------"
      sudo rm -rf /home/vagrant/open5gs
      echo "---------Finished installing UERANSIM ------"     
    SHELL
  end
end