# -*- mode: ruby -*-
# vi: set ft=ruby :

IPv4_ADDR = "192.168.56.120"

Vagrant.configure("2") do |config|

  config.vm.box = "../package.box"

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "private_network", ip: IPv4_ADDR

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    vb.cpus = "1"
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

end
