# -*- mode: ruby -*-
# vi: set ft=ruby :

# Variables
OPEN5GS_IPv4_ADDR = "192.168.56.100"
UERANSIM_IPv4_ADDR = "192.168.56.120"


Vagrant.configure("2") do |config|

  config.vm.box = "../package.box"
  def_provider = "virtualbox"
  
  # The following folders shall be synced and loaded in all VMs 
  config.vm.synced_folder "configs", "/configs"
  config.vm.synced_folder "scripts", "/home/vagrant/scripts"

  # VM #1: OPEN5GS 5G core network (All-in-one)
  config.vm.define "open5gs" do |open5gs|
    open5gs.vm.network "private_network", ip: OPEN5GS_IPv4_ADDR

    open5gs.vm.provider def_provider do |vb|
     # Customize the amount of cpu & memory on the VM:
     vb.memory = "1024"
     vb.cpus = "1"
    end

    # Open5gs VM bootstrap provisioning with a shell script.
    open5gs.vm.provision "shell", :privileged => true, inline: <<-SHELL
      echo "---------Removing UERANSIM--------"
      sudo rm -rf /home/vagrant/UERANSIM
      echo "---------Finished installing Open5GS ------"      
    SHELL
    
    config.trigger.after :up do |trigger|
      trigger.name = "Finished Message"
      trigger.info = "Machine is up!"
      config.vm.provision :shell, :run => 'always', :privileged => true, inline: <<-SHELL
        # This script will run everytime that the system bootsup 
        echo "--- Adding a route for the UE to have WAN connectivity over SGi/N6 -------"
        sudo sh /home/vagrant/open5gs/misc/netconf.sh
        ### Enable IPv4/IPv6 Forwarding
        sudo sysctl -w net.ipv4.ip_forward=1
        sudo sysctl -w net.ipv6.conf.all.forwarding=1
        ### Add NAT Rule
        sudo iptables -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o ogstun -j MASQUERADE
        sudo ip6tables -t nat -A POSTROUTING -s 2001:db8:cafe::/48 ! -o ogstun -j MASQUERADE
      SHELL
    end
  end

  # VM #2 : UERANSIM Simulator
  config.vm.define "ueransim" do |ueransim|
    ueransim.vm.network "private_network", ip: UERANSIM_IPv4_ADDR

    config.vm.synced_folder "configs", "/configs"

    # Customize the amount of cpu & memory on the VM:
    ueransim.vm.provider def_provider do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    # #Enable provisioning with a shell script.
    ueransim.vm.provision "shell", :privileged => true, inline:<<-SHELL 
      echo "---------Removing open5gs --------"
      sudo rm -rf /home/vagrant/open5gs
      echo "---------Finished installing UERANSIM ------"      
      SHELL

  end

end